# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import billing_details_pb2 as billing__details__pb2


class BillingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAdminBillStatus = channel.unary_unary(
                '/billing_details.BillingService/CheckAdminBillStatus',
                request_serializer=billing__details__pb2.RequestData.SerializeToString,
                response_deserializer=billing__details__pb2.ResponseData.FromString,
                )
        self.BillAdmin = channel.unary_unary(
                '/billing_details.BillingService/BillAdmin',
                request_serializer=billing__details__pb2.RequestData.SerializeToString,
                response_deserializer=billing__details__pb2.ResponseData.FromString,
                )


class BillingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckAdminBillStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BillAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAdminBillStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAdminBillStatus,
                    request_deserializer=billing__details__pb2.RequestData.FromString,
                    response_serializer=billing__details__pb2.ResponseData.SerializeToString,
            ),
            'BillAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.BillAdmin,
                    request_deserializer=billing__details__pb2.RequestData.FromString,
                    response_serializer=billing__details__pb2.ResponseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'billing_details.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckAdminBillStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/billing_details.BillingService/CheckAdminBillStatus',
            billing__details__pb2.RequestData.SerializeToString,
            billing__details__pb2.ResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BillAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/billing_details.BillingService/BillAdmin',
            billing__details__pb2.RequestData.SerializeToString,
            billing__details__pb2.ResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
