# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_monitoring_details_sdk.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(transaction_monitoring_details_sdk.proto\x12\"transaction_monitoring_details_sdk\"\xec\x01\n\x0bRequestData\x12\x45\n\x0cproduct_type\x18\x01 \x01(\x0e\x32/.transaction_monitoring_details_sdk.ProductType\x12^\n\x10request_metadata\x18\x02 \x03(\x0b\x32\x44.transaction_monitoring_details_sdk.RequestData.RequestMetadataEntry\x1a\x36\n\x14RequestMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc9\x01\n\x0cResponseData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x61\n\x11response_metadata\x18\x03 \x03(\x0b\x32\x46.transaction_monitoring_details_sdk.ResponseData.ResponseMetadataEntry\x1a\x37\n\x15ResponseMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x1c\n\x0bProductType\x12\r\n\tUSD_CARDS\x10\x00\x32\xa4\x02\n\x1cTransactionMonitoringService\x12{\n\x14\x43heckTransactionRisk\x12/.transaction_monitoring_details_sdk.RequestData\x1a\x30.transaction_monitoring_details_sdk.ResponseData\"\x00\x12\x86\x01\n\x1fWhitelistUserFromPotentialFraud\x12/.transaction_monitoring_details_sdk.RequestData\x1a\x30.transaction_monitoring_details_sdk.ResponseData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_monitoring_details_sdk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTDATA_REQUESTMETADATAENTRY']._options = None
  _globals['_REQUESTDATA_REQUESTMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_RESPONSEDATA_RESPONSEMETADATAENTRY']._options = None
  _globals['_RESPONSEDATA_RESPONSEMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_PRODUCTTYPE']._serialized_start=523
  _globals['_PRODUCTTYPE']._serialized_end=551
  _globals['_REQUESTDATA']._serialized_start=81
  _globals['_REQUESTDATA']._serialized_end=317
  _globals['_REQUESTDATA_REQUESTMETADATAENTRY']._serialized_start=263
  _globals['_REQUESTDATA_REQUESTMETADATAENTRY']._serialized_end=317
  _globals['_RESPONSEDATA']._serialized_start=320
  _globals['_RESPONSEDATA']._serialized_end=521
  _globals['_RESPONSEDATA_RESPONSEMETADATAENTRY']._serialized_start=466
  _globals['_RESPONSEDATA_RESPONSEMETADATAENTRY']._serialized_end=521
  _globals['_TRANSACTIONMONITORINGSERVICE']._serialized_start=554
  _globals['_TRANSACTIONMONITORINGSERVICE']._serialized_end=846
# @@protoc_insertion_point(module_scope)
