# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transaction_monitoring_details_sdk_pb2 as transaction__monitoring__details__sdk__pb2


class TransactionMonitoringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckTransactionRisk = channel.unary_unary(
                '/transaction_monitoring_details_sdk.TransactionMonitoringService/CheckTransactionRisk',
                request_serializer=transaction__monitoring__details__sdk__pb2.RequestData.SerializeToString,
                response_deserializer=transaction__monitoring__details__sdk__pb2.ResponseData.FromString,
                )
        self.WhitelistUserFromPotentialFraud = channel.unary_unary(
                '/transaction_monitoring_details_sdk.TransactionMonitoringService/WhitelistUserFromPotentialFraud',
                request_serializer=transaction__monitoring__details__sdk__pb2.RequestData.SerializeToString,
                response_deserializer=transaction__monitoring__details__sdk__pb2.ResponseData.FromString,
                )


class TransactionMonitoringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckTransactionRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhitelistUserFromPotentialFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionMonitoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckTransactionRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTransactionRisk,
                    request_deserializer=transaction__monitoring__details__sdk__pb2.RequestData.FromString,
                    response_serializer=transaction__monitoring__details__sdk__pb2.ResponseData.SerializeToString,
            ),
            'WhitelistUserFromPotentialFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.WhitelistUserFromPotentialFraud,
                    request_deserializer=transaction__monitoring__details__sdk__pb2.RequestData.FromString,
                    response_serializer=transaction__monitoring__details__sdk__pb2.ResponseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction_monitoring_details_sdk.TransactionMonitoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionMonitoringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckTransactionRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_monitoring_details_sdk.TransactionMonitoringService/CheckTransactionRisk',
            transaction__monitoring__details__sdk__pb2.RequestData.SerializeToString,
            transaction__monitoring__details__sdk__pb2.ResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WhitelistUserFromPotentialFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_monitoring_details_sdk.TransactionMonitoringService/WhitelistUserFromPotentialFraud',
            transaction__monitoring__details__sdk__pb2.RequestData.SerializeToString,
            transaction__monitoring__details__sdk__pb2.ResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
