# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: billing_details.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62illing_details.proto\x12\x0f\x62illing_details\"\xc0\x01\n\x0bRequestData\x12,\n\tbill_type\x18\x01 \x01(\x0e\x32\x19.billing_details.BillType\x12K\n\x10request_metadata\x18\x02 \x03(\x0b\x32\x31.billing_details.RequestData.RequestMetadataEntry\x1a\x36\n\x14RequestMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb6\x01\n\x0cResponseData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\x12N\n\x11response_metadata\x18\x03 \x03(\x0b\x32\x33.billing_details.ResponseData.ResponseMetadataEntry\x1a\x37\n\x15ResponseMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xda\x04\n\x08\x42illType\x12%\n!CARD_ISSUING_FEE_USD_VIRTUAL_CARD\x10\x00\x12)\n%CARD_MAINTENANCE_FEE_USD_VIRTUAL_CARD\x10\x01\x12)\n%CARD_TRANSACTION_FEE_USD_VIRTUAL_CARD\x10\x02\x12\x14\n\x10\x43\x41RD_REWARDS_FEE\x10\x03\x12%\n!CARD_ISSUING_FEE_NGN_VIRTUAL_CARD\x10\x04\x12)\n%CARD_MAINTENANCE_FEE_NGN_VIRTUAL_CARD\x10\x05\x12)\n%CARD_TRANSACTION_FEE_NGN_VIRTUAL_CARD\x10\x06\x12+\n\'ACCOUNT_ISSUING_FEE_USD_VIRTUAL_ACCOUNT\x10\x07\x12/\n+ACCOUNT_MAINTENANCE_FEE_USD_VIRTUAL_ACCOUNT\x10\x08\x12/\n+ACCOUNT_TRANSACTION_FEE_USD_VIRTUAL_ACCOUNT\x10\t\x12 \n\x1c\x43\x41RD_FX_FEE_USD_VIRTUAL_CARD\x10\n\x12+\n\'ACCOUNT_ISSUING_FEE_EUR_VIRTUAL_ACCOUNT\x10\x0b\x12/\n+ACCOUNT_MAINTENANCE_FEE_EUR_VIRTUAL_ACCOUNT\x10\x0c\x12/\n+ACCOUNT_TRANSACTION_FEE_EUR_VIRTUAL_ACCOUNT\x10\r2\xb3\x01\n\x0e\x42illingService\x12U\n\x14\x43heckAdminBillStatus\x12\x1c.billing_details.RequestData\x1a\x1d.billing_details.ResponseData\"\x00\x12J\n\tBillAdmin\x12\x1c.billing_details.RequestData\x1a\x1d.billing_details.ResponseData\"\x00\x62\x06proto3')

_BILLTYPE = DESCRIPTOR.enum_types_by_name['BillType']
BillType = enum_type_wrapper.EnumTypeWrapper(_BILLTYPE)
CARD_ISSUING_FEE_USD_VIRTUAL_CARD = 0
CARD_MAINTENANCE_FEE_USD_VIRTUAL_CARD = 1
CARD_TRANSACTION_FEE_USD_VIRTUAL_CARD = 2
CARD_REWARDS_FEE = 3
CARD_ISSUING_FEE_NGN_VIRTUAL_CARD = 4
CARD_MAINTENANCE_FEE_NGN_VIRTUAL_CARD = 5
CARD_TRANSACTION_FEE_NGN_VIRTUAL_CARD = 6
ACCOUNT_ISSUING_FEE_USD_VIRTUAL_ACCOUNT = 7
ACCOUNT_MAINTENANCE_FEE_USD_VIRTUAL_ACCOUNT = 8
ACCOUNT_TRANSACTION_FEE_USD_VIRTUAL_ACCOUNT = 9
CARD_FX_FEE_USD_VIRTUAL_CARD = 10
ACCOUNT_ISSUING_FEE_EUR_VIRTUAL_ACCOUNT = 11
ACCOUNT_MAINTENANCE_FEE_EUR_VIRTUAL_ACCOUNT = 12
ACCOUNT_TRANSACTION_FEE_EUR_VIRTUAL_ACCOUNT = 13


_REQUESTDATA = DESCRIPTOR.message_types_by_name['RequestData']
_REQUESTDATA_REQUESTMETADATAENTRY = _REQUESTDATA.nested_types_by_name['RequestMetadataEntry']
_RESPONSEDATA = DESCRIPTOR.message_types_by_name['ResponseData']
_RESPONSEDATA_RESPONSEMETADATAENTRY = _RESPONSEDATA.nested_types_by_name['ResponseMetadataEntry']
RequestData = _reflection.GeneratedProtocolMessageType('RequestData', (_message.Message,), {

  'RequestMetadataEntry' : _reflection.GeneratedProtocolMessageType('RequestMetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTDATA_REQUESTMETADATAENTRY,
    '__module__' : 'billing_details_pb2'
    # @@protoc_insertion_point(class_scope:billing_details.RequestData.RequestMetadataEntry)
    })
  ,
  'DESCRIPTOR' : _REQUESTDATA,
  '__module__' : 'billing_details_pb2'
  # @@protoc_insertion_point(class_scope:billing_details.RequestData)
  })
_sym_db.RegisterMessage(RequestData)
_sym_db.RegisterMessage(RequestData.RequestMetadataEntry)

ResponseData = _reflection.GeneratedProtocolMessageType('ResponseData', (_message.Message,), {

  'ResponseMetadataEntry' : _reflection.GeneratedProtocolMessageType('ResponseMetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSEDATA_RESPONSEMETADATAENTRY,
    '__module__' : 'billing_details_pb2'
    # @@protoc_insertion_point(class_scope:billing_details.ResponseData.ResponseMetadataEntry)
    })
  ,
  'DESCRIPTOR' : _RESPONSEDATA,
  '__module__' : 'billing_details_pb2'
  # @@protoc_insertion_point(class_scope:billing_details.ResponseData)
  })
_sym_db.RegisterMessage(ResponseData)
_sym_db.RegisterMessage(ResponseData.ResponseMetadataEntry)

_BILLINGSERVICE = DESCRIPTOR.services_by_name['BillingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTDATA_REQUESTMETADATAENTRY._options = None
  _REQUESTDATA_REQUESTMETADATAENTRY._serialized_options = b'8\001'
  _RESPONSEDATA_RESPONSEMETADATAENTRY._options = None
  _RESPONSEDATA_RESPONSEMETADATAENTRY._serialized_options = b'8\001'
  _BILLTYPE._serialized_start=423
  _BILLTYPE._serialized_end=1025
  _REQUESTDATA._serialized_start=43
  _REQUESTDATA._serialized_end=235
  _REQUESTDATA_REQUESTMETADATAENTRY._serialized_start=181
  _REQUESTDATA_REQUESTMETADATAENTRY._serialized_end=235
  _RESPONSEDATA._serialized_start=238
  _RESPONSEDATA._serialized_end=420
  _RESPONSEDATA_RESPONSEMETADATAENTRY._serialized_start=365
  _RESPONSEDATA_RESPONSEMETADATAENTRY._serialized_end=420
  _BILLINGSERVICE._serialized_start=1028
  _BILLINGSERVICE._serialized_end=1207
# @@protoc_insertion_point(module_scope)
